export const SET_LOGININFO = 'SET_LOGININFO'

export const SET_VDOITEM = 'SET_VDOITEM'

export const SET_STARITEM = 'SET_STARITEM'

export const RECOMMEND_MOVIEPAGE = 'RECOMMEND_MOVIEPAGE'

export const RECOMMEND_STARPAGE = 'RECOMMEND_STARPAGE'

export const MOVIE_INDEX = 'MOVIE_INDEX'

export const STAR_INDEX = 'STAR_INDEX'

export const ALLMOVIE_INDEX = 'ALLMOVIE_INDEX'

export const ALLSTAR_INDEX = 'ALLSTAR_INDEX'
